### ISSUE TITLE
Call stack exceeded

### ISSUE THREAD

**Issue by Arkk92** [Ojka91/element-core#40]
![image](https://user-images.githubusercontent.com/117123822/212273626-b3eae2b1-c676-40eb-b0a8-88b107c06ebc.png)

**Comment by Ojka91** [comment]
Recursivity spotted here https://github.com/Ojka91/element-core/blob/b7818c66b9b80cab1f17c63f1590fe571baf80cc/src/game/controllers/movement_manager.ts#L37 

To fix the issue asap

**Comment by Ojka91** [comment]
On the attatched image we can see the root of the problem:

![image](https://github.com/user-attachments/assets/98a2c347-2594-492d-94cc-8a33051b426f)

Method `isWindBlocked ` is called when a player turn ends, and a check if a Sage is trapped is triggered.
When the Sage is surrounded by winds, the method isWindBlocked checks if the wind blocks the sage to determine if the Sage is trapped or not.

When a bunch of winds surround the Sage, the method `isWindBlocked `uses recursivity to chain the wind effects.
But then this happens as shown in the image:

Origin (checked position) is [5,10], but wind is [5,10] as well. This makes` x_dir` and` y_dir` to be 0 (directions bounded) 
As the directions bounded are 0, the landing position will be the same as the origin position

```
        const landing_position: Position = {
            row: wind.position.row + jump_distance * y_dir, // jump_distance * y_dir = 0
            column: wind.position.column + jump_distance * x_dir,  jump_distance * x_dir = 0
        }
```

So then, the recursivity calls the same position in an infinity loop.

This happens because 

`return this.isWindBlocked(grid, landing_position, grid_controller.getGridCellByPosition(landing_position) as WindModel, counter++);`

Is passing as parameter the origin and the wind on the same position, instead of checking the following wind (landing_position+1 to the given axis)

**Comment by Arkk92** [comment]
Nice spot! There shall be a test for this specific issue. It looks reproducible so, having a test would help us not to mask other issues or side effect when fixing this.
